# Generated by Django 3.1.2 on 2021-02-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0002_blogwrite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogwrite',
        ),
    ]
