# Generated by Django 3.1.4 on 2021-02-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0006_auto_20210228_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=25),
        ),
    ]
