# Generated by Django 3.1.4 on 2021-03-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
