# Generated by Django 3.1.4 on 2021-03-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='photos/avatar.png', upload_to='profile'),
        ),
    ]
