# Generated by Django 3.1.4 on 2021-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0012_auto_20210305_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='files',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
