# Generated by Django 3.0.8 on 2021-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0013_auto_20210305_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='files',
            field=models.FileField(default='media/avatar.png', upload_to='media'),
        ),
    ]
