# Generated by Django 3.0.8 on 2021-03-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0015_auto_20210305_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='files',
            field=models.FileField(blank=True, default='media/avatar.png', upload_to='media'),
        ),
    ]
