# Generated by Django 3.0.8 on 2021-03-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0016_auto_20210305_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
