# Generated by Django 3.0.8 on 2021-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0017_auto_20210305_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='files',
            field=models.FileField(upload_to='media'),
        ),
    ]
