# Generated by Django 3.0.8 on 2021-03-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0018_auto_20210306_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='files',
            field=models.FileField(upload_to=''),
        ),
    ]
